[[main]]
  name = "About Us"
  url = "/"
  weight = 10

[[main]]
  name = "Vinosa Travel and Transport Services"
  parent = "About Us"
  pageRef = "about-us"
  weight = 1

[[main]]
  name = "Our Promise"
  parent = "About Us"
  pageRef = "about-us"
  weight = 2

  [[main]]
  name = "Meet The Team"
  parent = "About Us"
  pageRef = "about-us"
  weight = 3

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 30

        [[main]]
  name = "Case Zero Development [Featured!]"
  parent = "Blog"
  pageRef = "blog"
  weight = 1

      [[main]]
  name = "Our Travellers"
  parent = "Blog"
  pageRef = "blog"
  weight = 2

    [[main]]
  name = "What to Eat!"
  parent = "Blog"
  pageRef = "blog"
  weight = 3

    [[main]]
  name = "Where to Stay!"
  parent = "Blog"
  pageRef = "blog"
  weight = 4



[[main]]
  name = "Stay Connected"
  pageRef = "stay-connected"
  weight = 40

[[main]]
  name = "Book Now!"
  pageRef = "book-now"
  weight = 50


 [[footer]]
   name = "Sitemap"
   pageRef = "sitemap"
   weight = 40

    [[footer]]
   name = "Privacy Policy"
   pageRef = "documentation/privacy-policy"
   weight = 30

    [[footer]]
   name = "Terms and Conditions"
   pageRef = "documentation/terms-and-conditions"
   weight = 20